version: "3.5"

networks:
  app-network:
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_data/mariadb

services:
  mariadb:
    build: ./srcs/requirements/mariadb
    env_file:
      - ./srcs/.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  wordpress:
    build: ./srcs/requirements/wordpress
    env_file:
      - ./srcs/.env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    build: ./srcs/requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: unless-stopped
